package com.bi.util.charts.payoff_charts;

import java.util.Map;

import com.bi.constants.CityConstants;

public class AlbanyChart {
    public static Map<String,Double> map = Map.ofEntries(
        Map.entry(CityConstants.ATLANTA, 10.0),
        Map.entry(CityConstants.BALTIMORE, 3.5),
        Map.entry(CityConstants.BILLINGS, 21.0),
        Map.entry(CityConstants.BIRMINGHAM, 11.0),
        Map.entry(CityConstants.BOSTON, 2.0),
        Map.entry(CityConstants.BUFFALO, 3.0),
        Map.entry(CityConstants.BUTTE, 23.5),
        Map.entry(CityConstants.CASPER, 18.0),
        Map.entry(CityConstants.CHARLESTON, 9.5),
        Map.entry(CityConstants.CHARLOTTE, 7.5),
        Map.entry(CityConstants.CHATTENOOGA, 10.0),
        Map.entry(CityConstants.CHICAGO, 8.0),
        Map.entry(CityConstants.CINCINNATI, 7.0),
        Map.entry(CityConstants.CLEVELAND, 5.0),
        Map.entry(CityConstants.COLUMBUS, 6.0),
        Map.entry(CityConstants.DALLAS, 17.0),
        Map.entry(CityConstants.DENVER, 18.5),
        Map.entry(CityConstants.DES_MOINES, 12.0),
        Map.entry(CityConstants.DETROIT, 5.5),
        Map.entry(CityConstants.EL_PASO, 22.0),
        Map.entry(CityConstants.FARGO, 14.5),
        Map.entry(CityConstants.FORT_WORTH, 17.0),
        Map.entry(CityConstants.HOUSTON, 18.5),
        Map.entry(CityConstants.INDIANAPOLIS, 7.5),
        Map.entry(CityConstants.JACKSONVILLE, 11.0),
        Map.entry(CityConstants.KANSAS_CITY, 12.5),
        Map.entry(CityConstants.KNOXVILLE, 8.5),
        Map.entry(CityConstants.LAS_VEGAS, 28.0),
        Map.entry(CityConstants.LITTLE_ROCK, 13.5),
        Map.entry(CityConstants.LOS_ANGELES, 30.5),
        Map.entry(CityConstants.LOUISVILLE, 8.5),
        Map.entry(CityConstants.MEMPHIS, 12.5),
        Map.entry(CityConstants.MIAMI, 15.0),
        Map.entry(CityConstants.MILWAUKEE, 9.0),
        Map.entry(CityConstants.MINNEAPOLIS_ST_PAUL, 12.5),
        Map.entry(CityConstants.MOBILE, 13.5),
        Map.entry(CityConstants.NASHVILLE, 10.5),
        Map.entry(CityConstants.NEW_ORLEANS,15.0),
        Map.entry(CityConstants.NEW_YORK, 1.5),
        Map.entry(CityConstants.NORFOLK, 6.0),
        Map.entry(CityConstants.OKLAHOMA_CITY,15.5),
        Map.entry(CityConstants.OMAHA, 13.0),
        Map.entry(CityConstants.PHILADELPHIA, 2.5),
        Map.entry(CityConstants.PHOENIX, 27.5),
        Map.entry(CityConstants.PITTSBURGH, 5.5),
        Map.entry(CityConstants.POCATELLO, 23.5),
        Map.entry(CityConstants.PORTLAND_ME, 3.0),
        Map.entry(CityConstants.PORTLAND_OR, 30.0),
        Map.entry(CityConstants.PUEBLO, 18.5),
        Map.entry(CityConstants.RAPID_CITY, 17.0),
        Map.entry(CityConstants.RENO, 25.5),
        Map.entry(CityConstants.RICHMOND, 5.0),
        Map.entry(CityConstants.SACRAMENTO, 27.0),
        Map.entry(CityConstants.SALT_LAKE_CITY, 23.5),
        Map.entry(CityConstants.SAN_ANTONIO, 19.5),
        Map.entry(CityConstants.SAN_DIEGO, 31.5),
        Map.entry(CityConstants.SAN_FRANCISCO_OAKLAND, 31.0),
        Map.entry(CityConstants.SEATTLE, 31.5),
        Map.entry(CityConstants.SHREVEPORT, 16.0),
        Map.entry(CityConstants.SPOKANE, 26.5),
        Map.entry(CityConstants.ST_LOUIS, 10.0),
        Map.entry(CityConstants.TAMPA, 13.5),
        Map.entry(CityConstants.TUCUMCARI, 18.5),
        Map.entry(CityConstants.WASHINGTON_DC, 3.5)
    );
}
