package com.bi.util.charts.payoff_charts;

import java.util.Map;

import com.bi.constants.CityConstants;

public class BaltimoreChart {
    public static Map<String,Double> map = Map.ofEntries(
        Map.entry(CityConstants.ALBANY, 3.5),
        Map.entry(CityConstants.ATLANTA, 7.0),
        Map.entry(CityConstants.BILLINGS, 21.0),
        Map.entry(CityConstants.BIRMINGHAM, 8.0),
        Map.entry(CityConstants.BOSTON, 4.0),
        Map.entry(CityConstants.BUFFALO, 4.0),
        Map.entry(CityConstants.BUTTE, 23.0),
        Map.entry(CityConstants.CASPER, 18.0),
        Map.entry(CityConstants.CHARLESTON, 5.5),
        Map.entry(CityConstants.CHARLOTTE, 4.0),
        Map.entry(CityConstants.CHATTENOOGA, 6.5),
        Map.entry(CityConstants.CHICAGO, 8.0),
        Map.entry(CityConstants.CINCINNATI, 6.0),
        Map.entry(CityConstants.CLEVELAND, 4.5),
        Map.entry(CityConstants.COLUMBUS, 5.0),
        Map.entry(CityConstants.DALLAS, 14.5),
        Map.entry(CityConstants.DENVER, 18.0),
        Map.entry(CityConstants.DES_MOINES, 11.5),
        Map.entry(CityConstants.DETROIT, 6.0),
        Map.entry(CityConstants.EL_PASO, 21.0),
        Map.entry(CityConstants.FARGO, 14.5),
        Map.entry(CityConstants.FORT_WORTH, 14.5),
        Map.entry(CityConstants.HOUSTON, 15.0),
        Map.entry(CityConstants.INDIANAPOLIS, 7.0),
        Map.entry(CityConstants.JACKSONVILLE,8.0),
        Map.entry(CityConstants.KANSAS_CITY, 12.0),
        Map.entry(CityConstants.KNOXVILLE, 5.5),
        Map.entry(CityConstants.LAS_VEGAS, 27.5),
        Map.entry(CityConstants.LITTLE_ROCK, 11.0),
        Map.entry(CityConstants.LOS_ANGELES, 29.0),
        Map.entry(CityConstants.LOUISVILLE, 7.0),
        Map.entry(CityConstants.MEMPHIS, 9.5),
        Map.entry(CityConstants.MIAMI, 11.5),
        Map.entry(CityConstants.MILWAUKEE,8.0),
        Map.entry(CityConstants.MINNEAPOLIS_ST_PAUL,12.0),
        Map.entry(CityConstants.MOBILE, 10.5),
        Map.entry(CityConstants.NASHVILLE, 7.5),
        Map.entry(CityConstants.NEW_ORLEANS,11.5),
        Map.entry(CityConstants.NEW_YORK, 2.0),
        Map.entry(CityConstants.NORFOLK, 2.5),
        Map.entry(CityConstants.OKLAHOMA_CITY,14.5),
        Map.entry(CityConstants.OMAHA, 13.0),
        Map.entry(CityConstants.PHILADELPHIA, 1.0),
        Map.entry(CityConstants.PHOENIX, 27.0),
        Map.entry(CityConstants.PITTSBURGH, 3.5),
        Map.entry(CityConstants.POCATELLO, 23.5),
        Map.entry(CityConstants.PORTLAND_ME, 5.5),
        Map.entry(CityConstants.PORTLAND_OR, 30.5),
        Map.entry(CityConstants.PUEBLO, 18.0),
        Map.entry(CityConstants.RAPID_CITY, 17.0),
        Map.entry(CityConstants.RENO, 28.5),
        Map.entry(CityConstants.RICHMOND, 1.5),
        Map.entry(CityConstants.SACRAMENTO, 30.0),
        Map.entry(CityConstants.SALT_LAKE_CITY,23.0),
        Map.entry(CityConstants.SAN_ANTONIO, 17.0),
        Map.entry(CityConstants.SAN_DIEGO, 28.5),
        Map.entry(CityConstants.SAN_FRANCISCO_OAKLAND, 30.5),
        Map.entry(CityConstants.SEATTLE, 29.5),
        Map.entry(CityConstants.SHREVEPORT, 12.5),
        Map.entry(CityConstants.SPOKANE, 26.5),
        Map.entry(CityConstants.ST_LOUIS, 9.0),
        Map.entry(CityConstants.TAMPA, 10.0),
        Map.entry(CityConstants.TUCUMCARI, 18.5),
        Map.entry(CityConstants.WASHINGTON_DC, 0.5)
    );
}