package com.bi.util.charts.payoff_charts;

import java.util.Map;

import com.bi.constants.CityConstants;

public class BillingsChart {
    public static Map<String,Double> map = Map.ofEntries(
        Map.entry(CityConstants.ALBANY,21.0),
        Map.entry(CityConstants.ATLANTA, 19.0),
        Map.entry(CityConstants.BALTIMORE, 21.0),
        Map.entry(CityConstants.BIRMINGHAM, 18.0),
        Map.entry(CityConstants.BOSTON, 23.0),
        Map.entry(CityConstants.BUFFALO, 18.0),
        Map.entry(CityConstants.BUTTE, 2.5),
        Map.entry(CityConstants.CASPER, 3.5),
        Map.entry(CityConstants.CHARLESTON, 22.5),
        Map.entry(CityConstants.CHARLOTTE, 21.0),
        Map.entry(CityConstants.CHATTENOOGA, 18.0),
        Map.entry(CityConstants.CHICAGO, 13.0),
        Map.entry(CityConstants.CINCINNATI, 15.5),
        Map.entry(CityConstants.CLEVELAND, 16.0),
        Map.entry(CityConstants.COLUMBUS, 16.0),
        Map.entry(CityConstants.DALLAS, 15.0),
        Map.entry(CityConstants.DENVER, 6.5),
        Map.entry(CityConstants.DES_MOINES, 10.5),
        Map.entry(CityConstants.DETROIT, 15.5),
        Map.entry(CityConstants.EL_PASO, 14.0),
        Map.entry(CityConstants.FARGO, 6.5),
        Map.entry(CityConstants.FORT_WORTH, 15.0),
        Map.entry(CityConstants.HOUSTON, 17.5),
        Map.entry(CityConstants.INDIANAPOLIS, 14.5),
        Map.entry(CityConstants.JACKSONVILLE,22.5),
        Map.entry(CityConstants.KANSAS_CITY, 10.5),
        Map.entry(CityConstants.KNOXVILLE, 18.5),
        Map.entry(CityConstants.LAS_VEGAS, 11.0),
        Map.entry(CityConstants.LITTLE_ROCK, 15.5),
        Map.entry(CityConstants.LOS_ANGELES, 14.5),
        Map.entry(CityConstants.LOUISVILLE, 16.0),
        Map.entry(CityConstants.MEMPHIS, 15.5),
        Map.entry(CityConstants.MIAMI, 26.0),
        Map.entry(CityConstants.MILWAUKEE,12.0),
        Map.entry(CityConstants.MINNEAPOLIS_ST_PAUL,9.0),
        Map.entry(CityConstants.MOBILE, 19.0),
        Map.entry(CityConstants.NASHVILLE, 16.5),
        Map.entry(CityConstants.NEW_ORLEANS,19.0),
        Map.entry(CityConstants.NEW_YORK, 22.0),
        Map.entry(CityConstants.NORFOLK, 22.0),
        Map.entry(CityConstants.OKLAHOMA_CITY,14.0),
        Map.entry(CityConstants.OMAHA, 9.0),
        Map.entry(CityConstants.PHILADELPHIA, 21.0),
        Map.entry(CityConstants.PHOENIX, 19.0),
        Map.entry(CityConstants.PITTSBURGH, 17.5),
        Map.entry(CityConstants.POCATELLO, 5.0),
        Map.entry(CityConstants.PORTLAND_ME, 24.0),
        Map.entry(CityConstants.PORTLAND_OR, 9.5),
        Map.entry(CityConstants.PUEBLO, 7.5),
        Map.entry(CityConstants.RAPID_CITY, 5.0),
        Map.entry(CityConstants.RENO, 12.0),
        Map.entry(CityConstants.RICHMOND, 21.5),
        Map.entry(CityConstants.SACRAMENTO, 13.5),
        Map.entry(CityConstants.SALT_LAKE_CITY,6.5),
        Map.entry(CityConstants.SAN_ANTONIO, 17.5),
        Map.entry(CityConstants.SAN_DIEGO, 15.5),
        Map.entry(CityConstants.SAN_FRANCISCO_OAKLAND,14.0),
        Map.entry(CityConstants.SEATTLE, 9.0),
        Map.entry(CityConstants.SHREVEPORT, 16.0),
        Map.entry(CityConstants.SPOKANE, 6.0),
        Map.entry(CityConstants.ST_LOUIS, 13.0),
        Map.entry(CityConstants.TAMPA, 24.0),
        Map.entry(CityConstants.TUCUMCARI, 11.0),
        Map.entry(CityConstants.WASHINGTON_DC, 20.5)
    );
}