package com.bi.util.charts.payoff_charts;

import java.util.Map;

import com.bi.constants.CityConstants;

public class BirminghamChart {
    public static Map<String,Double> map = Map.ofEntries(
        Map.entry(CityConstants.ALBANY,11.0),
        Map.entry(CityConstants.ATLANTA, 1.5),
        Map.entry(CityConstants.BALTIMORE, 8.0),
        Map.entry(CityConstants.BILLINGS, 18.0),
        Map.entry(CityConstants.BOSTON, 12.0),
        Map.entry(CityConstants.BUFFALO, 9.0),
        Map.entry(CityConstants.BUTTE, 20.0),
        Map.entry(CityConstants.CASPER, 14.0),
        Map.entry(CityConstants.CHARLESTON, 5.0),
        Map.entry(CityConstants.CHARLOTTE, 4.0),
        Map.entry(CityConstants.CHATTENOOGA, 1.5),
        Map.entry(CityConstants.CHICAGO, 6.5),
        Map.entry(CityConstants.CINCINNATI, 5.0),
        Map.entry(CityConstants.CLEVELAND, 7.5),
        Map.entry(CityConstants.COLUMBUS, 6.0),
        Map.entry(CityConstants.DALLAS, 6.5),
        Map.entry(CityConstants.DENVER, 13.5),
        Map.entry(CityConstants.DES_MOINES, 8.0),
        Map.entry(CityConstants.DETROIT,7.5),
        Map.entry(CityConstants.EL_PASO, 13.0),
        Map.entry(CityConstants.FARGO, 13.0),
        Map.entry(CityConstants.FORT_WORTH, 6.5),
        Map.entry(CityConstants.HOUSTON, 7.0),
        Map.entry(CityConstants.INDIANAPOLIS, 5.0),
        Map.entry(CityConstants.JACKSONVILLE,4.5),
        Map.entry(CityConstants.KANSAS_CITY, 7.5),
        Map.entry(CityConstants.KNOXVILLE, 2.5),
        Map.entry(CityConstants.LAS_VEGAS, 23.5),
        Map.entry(CityConstants.LITTLE_ROCK, 4.0),
        Map.entry(CityConstants.LOS_ANGELES, 21.0),
        Map.entry(CityConstants.LOUISVILLE, 4.0),
        Map.entry(CityConstants.MEMPHIS, 2.5),
        Map.entry(CityConstants.MIAMI, 8.0),
        Map.entry(CityConstants.MILWAUKEE,7.5),
        Map.entry(CityConstants.MINNEAPOLIS_ST_PAUL,10.5),
        Map.entry(CityConstants.MOBILE, 3.0),
        Map.entry(CityConstants.NASHVILLE, 2.0),
        Map.entry(CityConstants.NEW_ORLEANS,3.5),
        Map.entry(CityConstants.NEW_YORK, 10.0),
        Map.entry(CityConstants.NORFOLK, 7.0),
        Map.entry(CityConstants.OKLAHOMA_CITY,7.5),
        Map.entry(CityConstants.OMAHA, 9.0),
        Map.entry(CityConstants.PHILADELPHIA, 9.0),
        Map.entry(CityConstants.PHOENIX, 17.5),
        Map.entry(CityConstants.PITTSBURGH, 8.0),
        Map.entry(CityConstants.POCATELLO, 20.5),
        Map.entry(CityConstants.PORTLAND_ME, 13.5),
        Map.entry(CityConstants.PORTLAND_OR, 26.5),
        Map.entry(CityConstants.PUEBLO, 13.5),
        Map.entry(CityConstants.RAPID_CITY,14.5),
        Map.entry(CityConstants.RENO, 23.0),
        Map.entry(CityConstants.RICHMOND, 7.5),
        Map.entry(CityConstants.SACRAMENTO, 24.0),
        Map.entry(CityConstants.SALT_LAKE_CITY,19.0),
        Map.entry(CityConstants.SAN_ANTONIO, 9.5),
        Map.entry(CityConstants.SAN_DIEGO, 21.0),
        Map.entry(CityConstants.SAN_FRANCISCO_OAKLAND,25.5),
        Map.entry(CityConstants.SEATTLE, 27.0),
        Map.entry(CityConstants.SHREVEPORT, 4.5),
        Map.entry(CityConstants.SPOKANE, 24.0),
        Map.entry(CityConstants.ST_LOUIS, 5.0),
        Map.entry(CityConstants.TAMPA, 6.0),
        Map.entry(CityConstants.TUCUMCARI, 11.5),
        Map.entry(CityConstants.WASHINGTON_DC, 7.5)
    );
}