package com.bi.util.charts.payoff_charts;

import java.util.Map;

import com.bi.constants.CityConstants;

public class BostonChart {
    public static Map<String,Double> map = Map.ofEntries(
        Map.entry(CityConstants.ALBANY,2.0),
        Map.entry(CityConstants.ATLANTA,11.0),
        Map.entry(CityConstants.BALTIMORE, 4.0),
        Map.entry(CityConstants.BILLINGS, 23.0),
        Map.entry(CityConstants.BIRMINGHAM, 12.0),
        Map.entry(CityConstants.BUFFALO, 5.0),
        Map.entry(CityConstants.BUTTE, 25.5),
        Map.entry(CityConstants.CASPER, 20.0),
        Map.entry(CityConstants.CHARLESTON, 9.5),
        Map.entry(CityConstants.CHARLOTTE, 8.5),
        Map.entry(CityConstants.CHATTENOOGA, 11.5),
        Map.entry(CityConstants.CHICAGO, 10.0),
        Map.entry(CityConstants.CINCINNATI, 9.5),
        Map.entry(CityConstants.CLEVELAND, 7.0),
        Map.entry(CityConstants.COLUMBUS, 8.0),
        Map.entry(CityConstants.DALLAS, 18.5),
        Map.entry(CityConstants.DENVER, 20.5),
        Map.entry(CityConstants.DES_MOINES, 14.0),
        Map.entry(CityConstants.DETROIT,7.5),
        Map.entry(CityConstants.EL_PASO, 24.0),
        Map.entry(CityConstants.FARGO, 16.5),
        Map.entry(CityConstants.FORT_WORTH, 19.5),
        Map.entry(CityConstants.HOUSTON, 19.5),
        Map.entry(CityConstants.INDIANAPOLIS, 9.5),
        Map.entry(CityConstants.JACKSONVILLE,12.0),
        Map.entry(CityConstants.KANSAS_CITY, 14.5),
        Map.entry(CityConstants.KNOXVILLE, 9.5),
        Map.entry(CityConstants.LAS_VEGAS, 30.0),
        Map.entry(CityConstants.LITTLE_ROCK, 15.0),
        Map.entry(CityConstants.LOS_ANGELES, 32.5),
        Map.entry(CityConstants.LOUISVILLE, 10.5),
        Map.entry(CityConstants.MEMPHIS, 14.0),
        Map.entry(CityConstants.MIAMI, 16.0),
        Map.entry(CityConstants.MILWAUKEE,11.0),
        Map.entry(CityConstants.MINNEAPOLIS_ST_PAUL,14.0),
        Map.entry(CityConstants.MOBILE, 14.5),
        Map.entry(CityConstants.NASHVILLE, 12.0),
        Map.entry(CityConstants.NEW_ORLEANS,15.5),
        Map.entry(CityConstants.NEW_YORK, 2.5),
        Map.entry(CityConstants.NORFOLK, 7.0),
        Map.entry(CityConstants.OKLAHOMA_CITY,17.5),
        Map.entry(CityConstants.OMAHA, 15.0),
        Map.entry(CityConstants.PHILADELPHIA, 3.0),
        Map.entry(CityConstants.PHOENIX, 29.5),
        Map.entry(CityConstants.PITTSBURGH, 6.5),
        Map.entry(CityConstants.POCATELLO, 25.5),
        Map.entry(CityConstants.PORTLAND_ME,1.0),
        Map.entry(CityConstants.PORTLAND_OR, 32.0),
        Map.entry(CityConstants.PUEBLO, 21.0),
        Map.entry(CityConstants.RAPID_CITY,20.5),
        Map.entry(CityConstants.RENO, 30.0),
        Map.entry(CityConstants.RICHMOND, 5.5),
        Map.entry(CityConstants.SACRAMENTO, 32.0),
        Map.entry(CityConstants.SALT_LAKE_CITY,25.5),
        Map.entry(CityConstants.SAN_ANTONIO, 21.0),
        Map.entry(CityConstants.SAN_DIEGO, 32.5),
        Map.entry(CityConstants.SAN_FRANCISCO_OAKLAND,33.0),
        Map.entry(CityConstants.SEATTLE, 3.5),
        Map.entry(CityConstants.SHREVEPORT, 16.5),
        Map.entry(CityConstants.SPOKANE, 28.5),
        Map.entry(CityConstants.ST_LOUIS, 12.0),
        Map.entry(CityConstants.TAMPA, 14.0),
        Map.entry(CityConstants.TUCUMCARI, 21.0),
        Map.entry(CityConstants.WASHINGTON_DC, 4.5)
    );
}