package com.bi.util.charts.payoff_charts;

import java.util.Map;

import com.bi.constants.CityConstants;

public class BuffaloChart {
    public static Map<String,Double> map = Map.ofEntries(
        Map.entry(CityConstants.ALBANY,3.0),
        Map.entry(CityConstants.ATLANTA,9.5),
        Map.entry(CityConstants.BALTIMORE,4.0),
        Map.entry(CityConstants.BILLINGS, 18.0),
        Map.entry(CityConstants.BIRMINGHAM, 9.0),
        Map.entry(CityConstants.BOSTON, 5.0),
        Map.entry(CityConstants.BUTTE, 20.5),
        Map.entry(CityConstants.CASPER, 15.0),
        Map.entry(CityConstants.CHARLESTON, 9.5),
        Map.entry(CityConstants.CHARLOTTE, 8.0),
        Map.entry(CityConstants.CHATTENOOGA, 8.0),
        Map.entry(CityConstants.CHICAGO, 5.0),
        Map.entry(CityConstants.CINCINNATI, 4.5),
        Map.entry(CityConstants.CLEVELAND, 2.0),
        Map.entry(CityConstants.COLUMBUS, 3.0),
        Map.entry(CityConstants.DALLAS, 14.0),
        Map.entry(CityConstants.DENVER, 15.5),
        Map.entry(CityConstants.DES_MOINES, 9.0),
        Map.entry(CityConstants.DETROIT,2.5),
        Map.entry(CityConstants.EL_PASO, 19.0),
        Map.entry(CityConstants.FARGO, 11.5),
        Map.entry(CityConstants.FORT_WORTH, 14.0),
        Map.entry(CityConstants.HOUSTON, 15.5),
        Map.entry(CityConstants.INDIANAPOLIS, 4.5),
        Map.entry(CityConstants.JACKSONVILLE,12.0),
        Map.entry(CityConstants.KANSAS_CITY, 9.5),
        Map.entry(CityConstants.KNOXVILLE, 7.5),
        Map.entry(CityConstants.LAS_VEGAS, 25.0),
        Map.entry(CityConstants.LITTLE_ROCK, 10.5),
        Map.entry(CityConstants.LOS_ANGELES, 27.5),
        Map.entry(CityConstants.LOUISVILLE, 5.5),
        Map.entry(CityConstants.MEMPHIS, 9.5),
        Map.entry(CityConstants.MIAMI, 15.5),
        Map.entry(CityConstants.MILWAUKEE, 6.0),
        Map.entry(CityConstants.MINNEAPOLIS_ST_PAUL,9.0),
        Map.entry(CityConstants.MOBILE, 12.0),
        Map.entry(CityConstants.NASHVILLE, 7.5),
        Map.entry(CityConstants.NEW_ORLEANS,13.0),
        Map.entry(CityConstants.NEW_YORK, 4.0),
        Map.entry(CityConstants.NORFOLK, 6.5),
        Map.entry(CityConstants.OKLAHOMA_CITY,12.5),
        Map.entry(CityConstants.OMAHA, 10.0),
        Map.entry(CityConstants.PHILADELPHIA, 4.0),
        Map.entry(CityConstants.PHOENIX, 24.5),
        Map.entry(CityConstants.PITTSBURGH, 2.5),
        Map.entry(CityConstants.POCATELLO, 20.5),
        Map.entry(CityConstants.PORTLAND_ME,6.0),
        Map.entry(CityConstants.PORTLAND_OR, 27.0),
        Map.entry(CityConstants.PUEBLO, 15.5),
        Map.entry(CityConstants.RAPID_CITY,14.0),
        Map.entry(CityConstants.RENO, 25.5),
        Map.entry(CityConstants.RICHMOND, 5.5),
        Map.entry(CityConstants.SACRAMENTO, 27.0),
        Map.entry(CityConstants.SALT_LAKE_CITY,20.5),
        Map.entry(CityConstants.SAN_ANTONIO, 16.5),
        Map.entry(CityConstants.SAN_DIEGO, 27.0),
        Map.entry(CityConstants.SAN_FRANCISCO_OAKLAND,28.0),
        Map.entry(CityConstants.SEATTLE, 26.5),
        Map.entry(CityConstants.SHREVEPORT, 14.0),
        Map.entry(CityConstants.SPOKANE, 23.5),
        Map.entry(CityConstants.ST_LOUIS,7.0),
        Map.entry(CityConstants.TAMPA, 14.0),
        Map.entry(CityConstants.TUCUMCARI, 16.5),
        Map.entry(CityConstants.WASHINGTON_DC, 4.5)
    );
}
