package com.bi.util.charts.payoff_charts;

import java.util.Map;

import com.bi.constants.CityConstants;

public class ButteChart {
    public static Map<String,Double> map = Map.ofEntries(
        Map.entry(CityConstants.ALBANY,23.5),
        Map.entry(CityConstants.ATLANTA,21.5),
        Map.entry(CityConstants.BALTIMORE,23.0),
        Map.entry(CityConstants.BILLINGS, 2.5),
        Map.entry(CityConstants.BIRMINGHAM, 20.0),
        Map.entry(CityConstants.BOSTON, 25.5),
        Map.entry(CityConstants.BUFFALO, 20.5),
        Map.entry(CityConstants.CASPER, 5.5),
        Map.entry(CityConstants.CHARLESTON, 26.0),
        Map.entry(CityConstants.CHARLOTTE, 17.5),
        Map.entry(CityConstants.CHATTENOOGA, 14.0),
        Map.entry(CityConstants.CHICAGO, 15.0),
        Map.entry(CityConstants.CINCINNATI, 18.0),
        Map.entry(CityConstants.CLEVELAND, 18.5),
        Map.entry(CityConstants.COLUMBUS, 18.5),
        Map.entry(CityConstants.DALLAS, 17.5),
        Map.entry(CityConstants.DENVER, 9.0),
        Map.entry(CityConstants.DES_MOINES, 14.0),
        Map.entry(CityConstants.DETROIT,18.0),
        Map.entry(CityConstants.EL_PASO, 16.0),
        Map.entry(CityConstants.FARGO, 9.0),
        Map.entry(CityConstants.FORT_WORTH, 17.0),
        Map.entry(CityConstants.HOUSTON, 20.0),
        Map.entry(CityConstants.INDIANAPOLIS, 17.0),
        Map.entry(CityConstants.JACKSONVILLE,24.5),
        Map.entry(CityConstants.KANSAS_CITY, 13.0),
        Map.entry(CityConstants.KNOXVILLE, 21.0),
        Map.entry(CityConstants.LAS_VEGAS, 9.0),
        Map.entry(CityConstants.LITTLE_ROCK, 18.0),
        Map.entry(CityConstants.LOS_ANGELES, 12.0),
        Map.entry(CityConstants.LOUISVILLE, 18.0),
        Map.entry(CityConstants.MEMPHIS, 17.5),
        Map.entry(CityConstants.MIAMI, 28.5),
        Map.entry(CityConstants.MILWAUKEE, 14.5),
        Map.entry(CityConstants.MINNEAPOLIS_ST_PAUL,11.0),
        Map.entry(CityConstants.MOBILE, 21.0),
        Map.entry(CityConstants.NASHVILLE, 18.5),
        Map.entry(CityConstants.NEW_ORLEANS,21.5),
        Map.entry(CityConstants.NEW_YORK, 24.0),
        Map.entry(CityConstants.NORFOLK, 25.0),
        Map.entry(CityConstants.OKLAHOMA_CITY,16.5),
        Map.entry(CityConstants.OMAHA, 11.5),
        Map.entry(CityConstants.PHILADELPHIA, 23.5),
        Map.entry(CityConstants.PHOENIX, 16.5),
        Map.entry(CityConstants.PITTSBURGH, 20.0),
        Map.entry(CityConstants.POCATELLO, 2.5),
        Map.entry(CityConstants.PORTLAND_ME,26.5),
        Map.entry(CityConstants.PORTLAND_OR,7.0),
        Map.entry(CityConstants.PUEBLO, 10.0),
        Map.entry(CityConstants.RAPID_CITY,7.5),
        Map.entry(CityConstants.RENO, 9.5),
        Map.entry(CityConstants.RICHMOND, 23.5),
        Map.entry(CityConstants.SACRAMENTO, 11.0),
        Map.entry(CityConstants.SALT_LAKE_CITY,4.5),
        Map.entry(CityConstants.SAN_ANTONIO, 19.5),
        Map.entry(CityConstants.SAN_DIEGO, 13.0),
        Map.entry(CityConstants.SAN_FRANCISCO_OAKLAND,12.0),
        Map.entry(CityConstants.SEATTLE, 6.5),
        Map.entry(CityConstants.SHREVEPORT,18.5),
        Map.entry(CityConstants.SPOKANE, 3.5),
        Map.entry(CityConstants.ST_LOUIS,15.5),
        Map.entry(CityConstants.TAMPA, 26.5),
        Map.entry(CityConstants.TUCUMCARI, 13.5),
        Map.entry(CityConstants.WASHINGTON_DC, 22.5)
    );
}
