package com.bi.util.charts.payoff_charts;

import java.util.Map;

import com.bi.constants.CityConstants;

public class CasperChart {
    public static Map<String,Double> map = Map.ofEntries(
        Map.entry(CityConstants.ALBANY,18.0),
        Map.entry(CityConstants.ATLANTA,25.5),
        Map.entry(CityConstants.BALTIMORE,18.0),
        Map.entry(CityConstants.BILLINGS, 3.5),
        Map.entry(CityConstants.BIRMINGHAM, 14.0),
        Map.entry(CityConstants.BOSTON, 20.0),
        Map.entry(CityConstants.BUFFALO, 15.0),
        Map.entry(CityConstants.BUTTE, 5.5),
        Map.entry(CityConstants.CHARLESTON, 19.0),
        Map.entry(CityConstants.CHARLOTTE, 17.5),
        Map.entry(CityConstants.CHATTENOOGA, 14.0),
        Map.entry(CityConstants.CHICAGO, 10.0),
        Map.entry(CityConstants.CINCINNATI, 12.5),
        Map.entry(CityConstants.CLEVELAND, 13.5),
        Map.entry(CityConstants.COLUMBUS, 13.0),
        Map.entry(CityConstants.DALLAS, 11.5),
        Map.entry(CityConstants.DENVER, 3.5),
        Map.entry(CityConstants.DES_MOINES, 6.5),
        Map.entry(CityConstants.DETROIT,12.5),
        Map.entry(CityConstants.EL_PASO, 9.5),
        Map.entry(CityConstants.FARGO, 7.5),
        Map.entry(CityConstants.FORT_WORTH, 11.5),
        Map.entry(CityConstants.HOUSTON, 14.5),
        Map.entry(CityConstants.INDIANAPOLIS, 11.5),
        Map.entry(CityConstants.JACKSONVILLE,18.5),
        Map.entry(CityConstants.KANSAS_CITY, 7.0),
        Map.entry(CityConstants.KNOXVILLE, 14.5),
        Map.entry(CityConstants.LAS_VEGAS, 12.0),
        Map.entry(CityConstants.LITTLE_ROCK, 11.5),
        Map.entry(CityConstants.LOS_ANGELES, 15.0),
        Map.entry(CityConstants.LOUISVILLE, 12.0),
        Map.entry(CityConstants.MEMPHIS, 12.0),
        Map.entry(CityConstants.MIAMI, 22.0),
        Map.entry(CityConstants.MILWAUKEE, 10.0),
        Map.entry(CityConstants.MINNEAPOLIS_ST_PAUL,8.0),
        Map.entry(CityConstants.MOBILE, 15.5),
        Map.entry(CityConstants.NASHVILLE, 12.5),
        Map.entry(CityConstants.NEW_ORLEANS,15.5),
        Map.entry(CityConstants.NEW_YORK, 19.0),
        Map.entry(CityConstants.NORFOLK, 19.0),
        Map.entry(CityConstants.OKLAHOMA_CITY,10.5),
        Map.entry(CityConstants.OMAHA, 5.5),
        Map.entry(CityConstants.PHILADELPHIA, 18.0),
        Map.entry(CityConstants.PHOENIX, 14.0),
        Map.entry(CityConstants.PITTSBURGH, 14.5),
        Map.entry(CityConstants.POCATELLO, 7.5),
        Map.entry(CityConstants.PORTLAND_ME,21.5),
        Map.entry(CityConstants.PORTLAND_OR,13.0),
        Map.entry(CityConstants.PUEBLO, 4.5),
        Map.entry(CityConstants.RAPID_CITY,3.0),
        Map.entry(CityConstants.RENO, 12.5),
        Map.entry(CityConstants.RICHMOND, 18.5),
        Map.entry(CityConstants.SACRAMENTO, 14.0),
        Map.entry(CityConstants.SALT_LAKE_CITY,7.5),
        Map.entry(CityConstants.SAN_ANTONIO, 14.0),
        Map.entry(CityConstants.SAN_DIEGO, 16.5),
        Map.entry(CityConstants.SAN_FRANCISCO_OAKLAND,15.0),
        Map.entry(CityConstants.SEATTLE, 12.5),
        Map.entry(CityConstants.SHREVEPORT,12.5),
        Map.entry(CityConstants.SPOKANE, 9.0),
        Map.entry(CityConstants.ST_LOUIS,10.0),
        Map.entry(CityConstants.TAMPA, 15.0),
        Map.entry(CityConstants.TUCUMCARI, 8.0),
        Map.entry(CityConstants.WASHINGTON_DC, 17.5)
    );
}
