package com.bi.util.charts.payoff_charts;

import java.util.Map;

import com.bi.constants.CityConstants;

public class CharlotteChart {
    public static Map<String,Double> map = Map.ofEntries(
        Map.entry(CityConstants.ALBANY,7.5),
        Map.entry(CityConstants.ATLANTA,2.5),
        Map.entry(CityConstants.BALTIMORE,4.0),
        Map.entry(CityConstants.BILLINGS, 21.0),
        Map.entry(CityConstants.BIRMINGHAM, 4.0),
        Map.entry(CityConstants.BOSTON, 8.5),
        Map.entry(CityConstants.BUFFALO, 8.0),
        Map.entry(CityConstants.BUTTE, 17.5),
        Map.entry(CityConstants.CASPER, 17.5),
        Map.entry(CityConstants.CHARLESTON, 2.5),
        Map.entry(CityConstants.CHATTENOOGA, 4.0),
        Map.entry(CityConstants.CHICAGO, 8.5),
        Map.entry(CityConstants.CINCINNATI, 5.5),
        Map.entry(CityConstants.CLEVELAND, 6.5),
        Map.entry(CityConstants.COLUMBUS, 6.0),
        Map.entry(CityConstants.DALLAS, 11.0),
        Map.entry(CityConstants.DENVER, 18.0),
        Map.entry(CityConstants.DES_MOINES, 11.5),
        Map.entry(CityConstants.DETROIT,8.0),
        Map.entry(CityConstants.EL_PASO, 17.5),
        Map.entry(CityConstants.FARGO, 15.0),
        Map.entry(CityConstants.FORT_WORTH, 11.0),
        Map.entry(CityConstants.HOUSTON, 11.0),
        Map.entry(CityConstants.INDIANAPOLIS, 6.5),
        Map.entry(CityConstants.JACKSONVILLE,4.0),
        Map.entry(CityConstants.KANSAS_CITY, 11.0),
        Map.entry(CityConstants.KNOXVILLE, 2.5),
        Map.entry(CityConstants.LAS_VEGAS, 26.0),
        Map.entry(CityConstants.LITTLE_ROCK, 8.5),
        Map.entry(CityConstants.LOS_ANGELES, 25.5),
        Map.entry(CityConstants.LOUISVILLE, 5.5),
        Map.entry(CityConstants.MEMPHIS, 7.0),
        Map.entry(CityConstants.MIAMI, 7.5),
        Map.entry(CityConstants.MILWAUKEE, 9.5),
        Map.entry(CityConstants.MINNEAPOLIS_ST_PAUL,12.5),
        Map.entry(CityConstants.MOBILE, 6.0),
        Map.entry(CityConstants.NASHVILLE, 5.0),
        Map.entry(CityConstants.NEW_ORLEANS,7.5),
        Map.entry(CityConstants.NEW_YORK, 6.0),
        Map.entry(CityConstants.NORFOLK, 4.0),
        Map.entry(CityConstants.OKLAHOMA_CITY,11.5),
        Map.entry(CityConstants.OMAHA, 12.5),
        Map.entry(CityConstants.PHILADELPHIA,5.0),
        Map.entry(CityConstants.PHOENIX, 24.0),
        Map.entry(CityConstants.PITTSBURGH, 6.0),
        Map.entry(CityConstants.POCATELLO, 23.0),
        Map.entry(CityConstants.PORTLAND_ME,9.5),
        Map.entry(CityConstants.PORTLAND_OR,30.5),
        Map.entry(CityConstants.PUEBLO, 18.0),
        Map.entry(CityConstants.RAPID_CITY,18.0),
        Map.entry(CityConstants.RENO, 27.5),
        Map.entry(CityConstants.RICHMOND,3.5),
        Map.entry(CityConstants.SACRAMENTO, 29.0),
        Map.entry(CityConstants.SALT_LAKE_CITY,22.5),
        Map.entry(CityConstants.SAN_ANTONIO, 13.5),
        Map.entry(CityConstants.SAN_DIEGO, 25.5),
        Map.entry(CityConstants.SAN_FRANCISCO_OAKLAND,30.0),
        Map.entry(CityConstants.SEATTLE, 30.0),
        Map.entry(CityConstants.SHREVEPORT,9.0),
        Map.entry(CityConstants.SPOKANE, 27.0),
        Map.entry(CityConstants.ST_LOUIS,8.0),
        Map.entry(CityConstants.TAMPA, 6.0),
        Map.entry(CityConstants.TUCUMCARI, 15.5),
        Map.entry(CityConstants.WASHINGTON_DC, 4.0)
    );
}
