package com.bi.util.charts.payoff_charts;

import java.util.Map;

import com.bi.constants.CityConstants;

public class CharlestonChart {
    public static Map<String,Double> map = Map.ofEntries(
        Map.entry(CityConstants.ALBANY,9.5),
        Map.entry(CityConstants.ATLANTA,3.0),
        Map.entry(CityConstants.BALTIMORE,5.5),
        Map.entry(CityConstants.BILLINGS, 22.5),
        Map.entry(CityConstants.BIRMINGHAM, 5.0),
        Map.entry(CityConstants.BOSTON, 9.5),
        Map.entry(CityConstants.BUFFALO, 9.5),
        Map.entry(CityConstants.BUTTE, 26.0),
        Map.entry(CityConstants.CASPER, 19.0),
        Map.entry(CityConstants.CHARLOTTE, 2.5),
        Map.entry(CityConstants.CHATTENOOGA, 4.5),
        Map.entry(CityConstants.CHICAGO, 10.0),
        Map.entry(CityConstants.CINCINNATI, 7.0),
        Map.entry(CityConstants.CLEVELAND, 9.5),
        Map.entry(CityConstants.COLUMBUS, 8.5),
        Map.entry(CityConstants.DALLAS, 11.5),
        Map.entry(CityConstants.DENVER, 18.5),
        Map.entry(CityConstants.DES_MOINES, 13.0),
        Map.entry(CityConstants.DETROIT,10.0),
        Map.entry(CityConstants.EL_PASO, 19.0),
        Map.entry(CityConstants.FARGO, 16.5),
        Map.entry(CityConstants.FORT_WORTH, 11.5),
        Map.entry(CityConstants.HOUSTON, 11.5),
        Map.entry(CityConstants.INDIANAPOLIS, 8.0),
        Map.entry(CityConstants.JACKSONVILLE,2.5),
        Map.entry(CityConstants.KANSAS_CITY, 12.0),
        Map.entry(CityConstants.KNOXVILLE, 4.0),
        Map.entry(CityConstants.LAS_VEGAS, 26.5),
        Map.entry(CityConstants.LITTLE_ROCK, 8.5),
        Map.entry(CityConstants.LOS_ANGELES, 26.0),
        Map.entry(CityConstants.LOUISVILLE, 7.0),
        Map.entry(CityConstants.MEMPHIS, 7.5),
        Map.entry(CityConstants.MIAMI, 6.0),
        Map.entry(CityConstants.MILWAUKEE, 11.0),
        Map.entry(CityConstants.MINNEAPOLIS_ST_PAUL,14.0),
        Map.entry(CityConstants.MOBILE, 6.0),
        Map.entry(CityConstants.NASHVILLE, 6.0),
        Map.entry(CityConstants.NEW_ORLEANS,7.5),
        Map.entry(CityConstants.NEW_YORK, 7.5),
        Map.entry(CityConstants.NORFOLK, 4.5),
        Map.entry(CityConstants.OKLAHOMA_CITY,12.0),
        Map.entry(CityConstants.OMAHA, 13.5),
        Map.entry(CityConstants.PHILADELPHIA, 8.0),
        Map.entry(CityConstants.PHOENIX, 22.5),
        Map.entry(CityConstants.PITTSBURGH, 8.0),
        Map.entry(CityConstants.POCATELLO, 24.0),
        Map.entry(CityConstants.PORTLAND_ME,11.0),
        Map.entry(CityConstants.PORTLAND_OR,31.0),
        Map.entry(CityConstants.PUEBLO, 18.5),
        Map.entry(CityConstants.RAPID_CITY,19.0),
        Map.entry(CityConstants.RENO, 29.5),
        Map.entry(CityConstants.RICHMOND, 4.0),
        Map.entry(CityConstants.SACRAMENTO, 31.0),
        Map.entry(CityConstants.SALT_LAKE_CITY,23.5),
        Map.entry(CityConstants.SAN_ANTONIO, 13.5),
        Map.entry(CityConstants.SAN_DIEGO, 26.0),
        Map.entry(CityConstants.SAN_FRANCISCO_OAKLAND,30.5),
        Map.entry(CityConstants.SEATTLE, 31.5),
        Map.entry(CityConstants.SHREVEPORT,9.5),
        Map.entry(CityConstants.SPOKANE, 28.0),
        Map.entry(CityConstants.ST_LOUIS,9.0),
        Map.entry(CityConstants.TAMPA, 4.5),
        Map.entry(CityConstants.TUCUMCARI, 16.0),
        Map.entry(CityConstants.WASHINGTON_DC, 5.0)
    );
}
