package com.bi.util.charts.payoff_charts;

import java.util.Map;

import com.bi.constants.CityConstants;

public class ChattanoogaChart {
    public static Map<String,Double> map = Map.ofEntries(
        Map.entry(CityConstants.ALBANY,10.0),
        Map.entry(CityConstants.ATLANTA,1.5),
        Map.entry(CityConstants.BALTIMORE,6.5),
        Map.entry(CityConstants.BILLINGS, 18.0),
        Map.entry(CityConstants.BIRMINGHAM, 1.5),
        Map.entry(CityConstants.BOSTON, 11.5),
        Map.entry(CityConstants.BUFFALO, 8.0),
        Map.entry(CityConstants.BUTTE, 14.0),
        Map.entry(CityConstants.CASPER, 14.0),
        Map.entry(CityConstants.CHARLESTON, 4.5),
        Map.entry(CityConstants.CHARLOTTE, 4.0),
        Map.entry(CityConstants.CHICAGO, 6.0),
        Map.entry(CityConstants.CINCINNATI, 3.5),
        Map.entry(CityConstants.CLEVELAND, 6.0),
        Map.entry(CityConstants.COLUMBUS, 4.5),
        Map.entry(CityConstants.DALLAS, 9.0),
        Map.entry(CityConstants.DENVER, 14.0),
        Map.entry(CityConstants.DES_MOINES, 8.0),
        Map.entry(CityConstants.DETROIT,6.0),
        Map.entry(CityConstants.EL_PASO, 15.5),
        Map.entry(CityConstants.FARGO, 12.5),
        Map.entry(CityConstants.FORT_WORTH, 9.0),
        Map.entry(CityConstants.HOUSTON, 8.5),
        Map.entry(CityConstants.INDIANAPOLIS, 4.5),
        Map.entry(CityConstants.JACKSONVILLE,5.0),
        Map.entry(CityConstants.KANSAS_CITY, 7.5),
        Map.entry(CityConstants.KNOXVILLE, 1.0),
        Map.entry(CityConstants.LAS_VEGAS, 24.0),
        Map.entry(CityConstants.LITTLE_ROCK, 5.5),
        Map.entry(CityConstants.LOS_ANGELES, 23.5),
        Map.entry(CityConstants.LOUISVILLE, 3.0),
        Map.entry(CityConstants.MEMPHIS, 4.0),
        Map.entry(CityConstants.MIAMI, 8.5),
        Map.entry(CityConstants.MILWAUKEE, 7.0),
        Map.entry(CityConstants.MINNEAPOLIS_ST_PAUL,10.0),
        Map.entry(CityConstants.MOBILE, 5.0),
        Map.entry(CityConstants.NASHVILLE, 1.5),
        Map.entry(CityConstants.NEW_ORLEANS,6.5),
        Map.entry(CityConstants.NEW_YORK, 8.5),
        Map.entry(CityConstants.NORFOLK, 6.5),
        Map.entry(CityConstants.OKLAHOMA_CITY,9.0),
        Map.entry(CityConstants.OMAHA, 9.0),
        Map.entry(CityConstants.PHILADELPHIA,7.5),
        Map.entry(CityConstants.PHOENIX, 19.0),
        Map.entry(CityConstants.PITTSBURGH, 7.0),
        Map.entry(CityConstants.POCATELLO, 21.5),
        Map.entry(CityConstants.PORTLAND_ME,12.0),
        Map.entry(CityConstants.PORTLAND_OR,26.5),
        Map.entry(CityConstants.PUEBLO, 14.0),
        Map.entry(CityConstants.RAPID_CITY,14.5),
        Map.entry(CityConstants.RENO, 24.5),
        Map.entry(CityConstants.RICHMOND,6.0),
        Map.entry(CityConstants.SACRAMENTO, 26.0),
        Map.entry(CityConstants.SALT_LAKE_CITY,20.5),
        Map.entry(CityConstants.SAN_ANTONIO, 10.5),
        Map.entry(CityConstants.SAN_DIEGO, 23.5),
        Map.entry(CityConstants.SAN_FRANCISCO_OAKLAND,27.0),
        Map.entry(CityConstants.SEATTLE, 27.0),
        Map.entry(CityConstants.SHREVEPORT,7.0),
        Map.entry(CityConstants.SPOKANE, 18.5),
        Map.entry(CityConstants.ST_LOUIS,4.5),
        Map.entry(CityConstants.TAMPA, 2.0),
        Map.entry(CityConstants.TUCUMCARI, 13.0),
        Map.entry(CityConstants.WASHINGTON_DC, 6.0)
    );
}
