package com.bi.util.charts.payoff_charts;

import java.util.Map;

import com.bi.constants.CityConstants;

public class ChicagoChart {
    public static Map<String,Double> map = Map.ofEntries(
        Map.entry(CityConstants.ALBANY,8.0),
        Map.entry(CityConstants.ATLANTA,7.5),
        Map.entry(CityConstants.BALTIMORE,8.0),
        Map.entry(CityConstants.BILLINGS, 13.0),
        Map.entry(CityConstants.BIRMINGHAM, 6.5),
        Map.entry(CityConstants.BOSTON, 10.0),
        Map.entry(CityConstants.BUFFALO, 5.0),
        Map.entry(CityConstants.BUTTE, 15.0),
        Map.entry(CityConstants.CASPER, 10.0),
        Map.entry(CityConstants.CHARLESTON, 10.0),
        Map.entry(CityConstants.CHARLOTTE, 8.5),
        Map.entry(CityConstants.CHATTENOOGA, 6.0),
        Map.entry(CityConstants.CINCINNATI, 3.0),
        Map.entry(CityConstants.CLEVELAND, 3.5),
        Map.entry(CityConstants.COLUMBUS, 3.5),
        Map.entry(CityConstants.DALLAS, 9.5),
        Map.entry(CityConstants.DENVER, 10.5),
        Map.entry(CityConstants.DES_MOINES, 3.5),
        Map.entry(CityConstants.DETROIT,2.5),
        Map.entry(CityConstants.EL_PASO, 14.0),
        Map.entry(CityConstants.FARGO, 6.5),
        Map.entry(CityConstants.FORT_WORTH, 6.5),
        Map.entry(CityConstants.HOUSTON, 12.0),
        Map.entry(CityConstants.INDIANAPOLIS, 2.0),
        Map.entry(CityConstants.JACKSONVILLE,11.0),
        Map.entry(CityConstants.KANSAS_CITY, 4.5),
        Map.entry(CityConstants.KNOXVILLE, 5.5),
        Map.entry(CityConstants.LAS_VEGAS, 22.5),
        Map.entry(CityConstants.LITTLE_ROCK, 6.5),
        Map.entry(CityConstants.LOS_ANGELES, 22.5),
        Map.entry(CityConstants.LOUISVILLE, 3.0),
        Map.entry(CityConstants.MEMPHIS, 5.5),
        Map.entry(CityConstants.MIAMI, 14.5),
        Map.entry(CityConstants.MILWAUKEE, 1.0),
        Map.entry(CityConstants.MINNEAPOLIS_ST_PAUL,4.0),
        Map.entry(CityConstants.MOBILE, 8.5),
        Map.entry(CityConstants.NASHVILLE, 4.5),
        Map.entry(CityConstants.NEW_ORLEANS,9.0),
        Map.entry(CityConstants.NEW_YORK, 9.0),
        Map.entry(CityConstants.NORFOLK, 9.5),
        Map.entry(CityConstants.OKLAHOMA_CITY,8.0),
        Map.entry(CityConstants.OMAHA, 5.0),
        Map.entry(CityConstants.PHILADELPHIA,8.0),
        Map.entry(CityConstants.PHOENIX, 19.5),
        Map.entry(CityConstants.PITTSBURGH, 4.5),
        Map.entry(CityConstants.POCATELLO, 15.0),
        Map.entry(CityConstants.PORTLAND_ME,11.5),
        Map.entry(CityConstants.PORTLAND_OR,22.0),
        Map.entry(CityConstants.PUEBLO, 10.5),
        Map.entry(CityConstants.RAPID_CITY,9.0),
        Map.entry(CityConstants.RENO, 20.0),
        Map.entry(CityConstants.RICHMOND,8.5),
        Map.entry(CityConstants.SACRAMENTO, 22.0),
        Map.entry(CityConstants.SALT_LAKE_CITY,15.0),
        Map.entry(CityConstants.SAN_ANTONIO, 12.0),
        Map.entry(CityConstants.SAN_DIEGO, 22.0),
        Map.entry(CityConstants.SAN_FRANCISCO_OAKLAND,22.5),
        Map.entry(CityConstants.SEATTLE, 21.5),
        Map.entry(CityConstants.SHREVEPORT,8.5),
        Map.entry(CityConstants.SPOKANE, 18.5),
        Map.entry(CityConstants.ST_LOUIS,3.0),
        Map.entry(CityConstants.TAMPA, 12.5),
        Map.entry(CityConstants.TUCUMCARI, 11.0),
        Map.entry(CityConstants.WASHINGTON_DC, 7.5)
    );
}
