package com.bi.util.charts.payoff_charts;

import java.util.Map;

import com.bi.constants.CityConstants;

public class CincinnatiChart {
    public static Map<String,Double> map = Map.ofEntries(
        Map.entry(CityConstants.ALBANY,7.0),
        Map.entry(CityConstants.ATLANTA,5.0),
        Map.entry(CityConstants.BALTIMORE,6.0),
        Map.entry(CityConstants.BILLINGS, 15.5),
        Map.entry(CityConstants.BIRMINGHAM, 5.0),
        Map.entry(CityConstants.BOSTON, 9.5),
        Map.entry(CityConstants.BUFFALO, 4.5),
        Map.entry(CityConstants.BUTTE, 18.0),
        Map.entry(CityConstants.CASPER, 12.5),
        Map.entry(CityConstants.CHARLESTON, 7.0),
        Map.entry(CityConstants.CHARLOTTE, 5.5),
        Map.entry(CityConstants.CHATTENOOGA, 3.5),
        Map.entry(CityConstants.CHICAGO, 3.0),
        Map.entry(CityConstants.CLEVELAND, 2.5),
        Map.entry(CityConstants.COLUMBUS, 1.0),
        Map.entry(CityConstants.DALLAS, 9.5),
        Map.entry(CityConstants.DENVER, 12.5),
        Map.entry(CityConstants.DES_MOINES, 6.5),
        Map.entry(CityConstants.DETROIT,2.5),
        Map.entry(CityConstants.EL_PASO, 15.5),
        Map.entry(CityConstants.FARGO, 9.0),
        Map.entry(CityConstants.FORT_WORTH, 9.5),
        Map.entry(CityConstants.HOUSTON, 12.5),
        Map.entry(CityConstants.INDIANAPOLIS, 1.0),
        Map.entry(CityConstants.JACKSONVILLE,8.5),
        Map.entry(CityConstants.KANSAS_CITY, 6.0),
        Map.entry(CityConstants.KNOXVILLE, 3.0),
        Map.entry(CityConstants.LAS_VEGAS, 22.5),
        Map.entry(CityConstants.LITTLE_ROCK, 6.5),
        Map.entry(CityConstants.LOS_ANGELES, 23.5),
        Map.entry(CityConstants.LOUISVILLE, 1.0),
        Map.entry(CityConstants.MEMPHIS, 5.0),
        Map.entry(CityConstants.MIAMI, 12.0),
        Map.entry(CityConstants.MILWAUKEE, 3.5),
        Map.entry(CityConstants.MINNEAPOLIS_ST_PAUL,7.0),
        Map.entry(CityConstants.MOBILE, 7.5),
        Map.entry(CityConstants.NASHVILLE, 3.0),
        Map.entry(CityConstants.NEW_ORLEANS,8.5),
        Map.entry(CityConstants.NEW_YORK, 7.5),
        Map.entry(CityConstants.NORFOLK, 7.0),
        Map.entry(CityConstants.OKLAHOMA_CITY,9.0),
        Map.entry(CityConstants.OMAHA, 7.5),
        Map.entry(CityConstants.PHILADELPHIA,6.5),
        Map.entry(CityConstants.PHOENIX, 21.0),
        Map.entry(CityConstants.PITTSBURGH, 3.0),
        Map.entry(CityConstants.POCATELLO, 18.0),
        Map.entry(CityConstants.PORTLAND_ME,10.5),
        Map.entry(CityConstants.PORTLAND_OR,24.5),
        Map.entry(CityConstants.PUEBLO, 12.5),
        Map.entry(CityConstants.RAPID_CITY,12.0),
        Map.entry(CityConstants.RENO, 23.0),
        Map.entry(CityConstants.RICHMOND,6.0),
        Map.entry(CityConstants.SACRAMENTO, 24.5),
        Map.entry(CityConstants.SALT_LAKE_CITY,18.0),
        Map.entry(CityConstants.SAN_ANTONIO, 12.5),
        Map.entry(CityConstants.SAN_DIEGO, 23.5),
        Map.entry(CityConstants.SAN_FRANCISCO_OAKLAND,25.5),
        Map.entry(CityConstants.SEATTLE, 24.0),
        Map.entry(CityConstants.SHREVEPORT,8.5),
        Map.entry(CityConstants.SPOKANE, 21.0),
        Map.entry(CityConstants.ST_LOUIS,3.5),
        Map.entry(CityConstants.TAMPA, 10.0),
        Map.entry(CityConstants.TUCUMCARI, 12.5),
        Map.entry(CityConstants.WASHINGTON_DC, 5.5)
    );
}
