package com.bi.util.charts.payoff_charts;

import java.util.Map;

import com.bi.constants.CityConstants;

public class ClevelandChart {
    public static Map<String,Double> map = Map.ofEntries(
        Map.entry(CityConstants.ALBANY,5.0),
        Map.entry(CityConstants.ATLANTA,7.5),
        Map.entry(CityConstants.BALTIMORE,4.5),
        Map.entry(CityConstants.BILLINGS, 16.0),
        Map.entry(CityConstants.BIRMINGHAM, 7.5),
        Map.entry(CityConstants.BOSTON, 7.0),
        Map.entry(CityConstants.BUFFALO, 2.0),
        Map.entry(CityConstants.BUTTE, 18.5),
        Map.entry(CityConstants.CASPER, 13.5),
        Map.entry(CityConstants.CHARLESTON, 9.5),
        Map.entry(CityConstants.CHARLOTTE, 6.5),
        Map.entry(CityConstants.CHATTENOOGA, 6.0),
        Map.entry(CityConstants.CHICAGO, 3.5),
        Map.entry(CityConstants.CINCINNATI, 2.5),
        Map.entry(CityConstants.COLUMBUS, 1.5),
        Map.entry(CityConstants.DALLAS, 12.5),
        Map.entry(CityConstants.DENVER, 13.5),
        Map.entry(CityConstants.DES_MOINES, 7.0),
        Map.entry(CityConstants.DETROIT,1.5),
        Map.entry(CityConstants.EL_PASO, 17.5),
        Map.entry(CityConstants.FARGO, 10.0),
        Map.entry(CityConstants.FORT_WORTH, 12.5),
        Map.entry(CityConstants.HOUSTON, 13.5),
        Map.entry(CityConstants.INDIANAPOLIS, 3.0),
        Map.entry(CityConstants.JACKSONVILLE,11.0),
        Map.entry(CityConstants.KANSAS_CITY, 8.0),
        Map.entry(CityConstants.KNOXVILLE, 5.5),
        Map.entry(CityConstants.LAS_VEGAS, 23.0),
        Map.entry(CityConstants.LITTLE_ROCK, 9.0),
        Map.entry(CityConstants.LOS_ANGELES, 25.5),
        Map.entry(CityConstants.LOUISVILLE, 3.5),
        Map.entry(CityConstants.MEMPHIS, 7.0),
        Map.entry(CityConstants.MIAMI, 14.5),
        Map.entry(CityConstants.MILWAUKEE, 4.0),
        Map.entry(CityConstants.MINNEAPOLIS_ST_PAUL,7.5),
        Map.entry(CityConstants.MOBILE, 10.0),
        Map.entry(CityConstants.NASHVILLE, 5.5),
        Map.entry(CityConstants.NEW_ORLEANS,11.0),
        Map.entry(CityConstants.NEW_YORK, 5.5),
        Map.entry(CityConstants.NORFOLK, 6.5),
        Map.entry(CityConstants.OKLAHOMA_CITY,10.5),
        Map.entry(CityConstants.OMAHA, 8.5),
        Map.entry(CityConstants.PHILADELPHIA,5.0),
        Map.entry(CityConstants.PHOENIX, 22.5),
        Map.entry(CityConstants.PITTSBURGH, 1.5),
        Map.entry(CityConstants.POCATELLO, 19.0),
        Map.entry(CityConstants.PORTLAND_ME,8.0),
        Map.entry(CityConstants.PORTLAND_OR,25.5),
        Map.entry(CityConstants.PUEBLO, 13.5),
        Map.entry(CityConstants.RAPID_CITY,12.5),
        Map.entry(CityConstants.RENO, 23.5),
        Map.entry(CityConstants.RICHMOND,5.5),
        Map.entry(CityConstants.SACRAMENTO, 25.0),
        Map.entry(CityConstants.SALT_LAKE_CITY,18.5),
        Map.entry(CityConstants.SAN_ANTONIO, 14.5),
        Map.entry(CityConstants.SAN_DIEGO, 25.0),
        Map.entry(CityConstants.SAN_FRANCISCO_OAKLAND,26.0),
        Map.entry(CityConstants.SEATTLE, 25.0),
        Map.entry(CityConstants.SHREVEPORT,11.0),
        Map.entry(CityConstants.SPOKANE, 21.5),
        Map.entry(CityConstants.ST_LOUIS,5.0),
        Map.entry(CityConstants.TAMPA, 12.5),
        Map.entry(CityConstants.TUCUMCARI, 14.5),
        Map.entry(CityConstants.WASHINGTON_DC, 4.5)
    );
}
