package com.bi.util.charts.payoff_charts;

import java.util.Map;

import com.bi.constants.CityConstants;

public class ColumbusChart {
    public static Map<String,Double> map = Map.ofEntries(
        Map.entry(CityConstants.ALBANY,6.0),
        Map.entry(CityConstants.ATLANTA,6.0),
        Map.entry(CityConstants.BALTIMORE,5.0),
        Map.entry(CityConstants.BILLINGS, 16.0),
        Map.entry(CityConstants.BIRMINGHAM, 6.0),
        Map.entry(CityConstants.BOSTON, 8.0),
        Map.entry(CityConstants.BUFFALO, 3.0),
        Map.entry(CityConstants.BUTTE, 18.5),
        Map.entry(CityConstants.CASPER, 13.0),
        Map.entry(CityConstants.CHARLESTON, 8.5),
        Map.entry(CityConstants.CHARLOTTE, 6.0),
        Map.entry(CityConstants.CHATTENOOGA, 4.5),
        Map.entry(CityConstants.CHICAGO, 3.5),
        Map.entry(CityConstants.CINCINNATI, 1.0),
        Map.entry(CityConstants.CLEVELAND, 1.5),
        Map.entry(CityConstants.DALLAS, 11.0),
        Map.entry(CityConstants.DENVER, 13.0),
        Map.entry(CityConstants.DES_MOINES, 7.0),
        Map.entry(CityConstants.DETROIT,2.0),
        Map.entry(CityConstants.EL_PASO, 17.0),
        Map.entry(CityConstants.FARGO, 9.5),
        Map.entry(CityConstants.FORT_WORTH, 11.0),
        Map.entry(CityConstants.HOUSTON, 13.0),
        Map.entry(CityConstants.INDIANAPOLIS, 1.5),
        Map.entry(CityConstants.JACKSONVILLE,9.5),
        Map.entry(CityConstants.KANSAS_CITY, 6.5),
        Map.entry(CityConstants.KNOXVILLE, 4.0),
        Map.entry(CityConstants.LAS_VEGAS, 22.5),
        Map.entry(CityConstants.LITTLE_ROCK, 6.5),
        Map.entry(CityConstants.LOS_ANGELES, 24.0),
        Map.entry(CityConstants.LOUISVILLE, 2.5),
        Map.entry(CityConstants.MEMPHIS, 6.0),
        Map.entry(CityConstants.MIAMI, 13.0),
        Map.entry(CityConstants.MILWAUKEE, 4.0),
        Map.entry(CityConstants.MINNEAPOLIS_ST_PAUL,7.5),
        Map.entry(CityConstants.MOBILE, 8.0),
        Map.entry(CityConstants.NASHVILLE, 4.0),
        Map.entry(CityConstants.NEW_ORLEANS,9.5),
        Map.entry(CityConstants.NEW_YORK, 6.5),
        Map.entry(CityConstants.NORFOLK, 7.0),
        Map.entry(CityConstants.OKLAHOMA_CITY,10.0),
        Map.entry(CityConstants.OMAHA, 8.0),
        Map.entry(CityConstants.PHILADELPHIA,5.5),
        Map.entry(CityConstants.PHOENIX, 21.5),
        Map.entry(CityConstants.PITTSBURGH, 2.0),
        Map.entry(CityConstants.POCATELLO, 18.5),
        Map.entry(CityConstants.PORTLAND_ME,9.5),
        Map.entry(CityConstants.PORTLAND_OR,25.5),
        Map.entry(CityConstants.PUEBLO, 13.0),
        Map.entry(CityConstants.RAPID_CITY,13.5),
        Map.entry(CityConstants.RENO, 23.5),
        Map.entry(CityConstants.RICHMOND,5.5),
        Map.entry(CityConstants.SACRAMENTO, 25.0),
        Map.entry(CityConstants.SALT_LAKE_CITY,18.0),
        Map.entry(CityConstants.SAN_ANTONIO, 13.5),
        Map.entry(CityConstants.SAN_DIEGO, 24.0),
        Map.entry(CityConstants.SAN_FRANCISCO_OAKLAND,26.5),
        Map.entry(CityConstants.SEATTLE, 25.0),
        Map.entry(CityConstants.SHREVEPORT,11.5),
        Map.entry(CityConstants.SPOKANE, 21.5),
        Map.entry(CityConstants.ST_LOUIS,4.0),
        Map.entry(CityConstants.TAMPA, 11.5),
        Map.entry(CityConstants.TUCUMCARI, 14.0),
        Map.entry(CityConstants.WASHINGTON_DC, 5.0)
    );
}
