package com.bi.util.charts.payoff_charts;

import java.util.Map;

import com.bi.constants.CityConstants;

public class DallasChart {
    public static Map<String,Double> map = Map.ofEntries(
        Map.entry(CityConstants.ALBANY,17.0),
        Map.entry(CityConstants.ATLANTA,8.0),
        Map.entry(CityConstants.BALTIMORE,14.5),
        Map.entry(CityConstants.BILLINGS, 15.0),
        Map.entry(CityConstants.BIRMINGHAM, 6.5),
        Map.entry(CityConstants.BOSTON, 18.5),
        Map.entry(CityConstants.BUFFALO, 14.0),
        Map.entry(CityConstants.BUTTE, 17.5),
        Map.entry(CityConstants.CASPER, 11.5),
        Map.entry(CityConstants.CHARLESTON, 11.5),
        Map.entry(CityConstants.CHARLOTTE, 11.0),
        Map.entry(CityConstants.CHATTENOOGA, 9.0),
        Map.entry(CityConstants.CHICAGO, 9.5),
        Map.entry(CityConstants.CINCINNATI, 9.5),
        Map.entry(CityConstants.CLEVELAND, 12.5),
        Map.entry(CityConstants.COLUMBUS , 11.0),
        Map.entry(CityConstants.DENVER, 8.5),
        Map.entry(CityConstants.DES_MOINES, 7.5),
        Map.entry(CityConstants.DETROIT,12.0),
        Map.entry(CityConstants.EL_PASO, 6.5),
        Map.entry(CityConstants.FARGO, 12.5),
        Map.entry(CityConstants.FORT_WORTH, 0.5),
        Map.entry(CityConstants.HOUSTON, 2.5),
        Map.entry(CityConstants.INDIANAPOLIS, 9.5),
        Map.entry(CityConstants.JACKSONVILLE,11.0),
        Map.entry(CityConstants.KANSAS_CITY, 5.0),
        Map.entry(CityConstants.KNOXVILLE, 9.0),
        Map.entry(CityConstants.LAS_VEGAS, 15.0),
        Map.entry(CityConstants.LITTLE_ROCK, 3.5),
        Map.entry(CityConstants.LOS_ANGELES, 14.5),
        Map.entry(CityConstants.LOUISVILLE, 8.5),
        Map.entry(CityConstants.MEMPHIS, 9.0),
        Map.entry(CityConstants.MIAMI, 14.5),
        Map.entry(CityConstants.MILWAUKEE, 10.5),
        Map.entry(CityConstants.MINNEAPOLIS_ST_PAUL,10.0),
        Map.entry(CityConstants.MOBILE, 6.0),
        Map.entry(CityConstants.NASHVILLE, 7.0),
        Map.entry(CityConstants.NEW_ORLEANS,5.0),
        Map.entry(CityConstants.NEW_YORK, 16.0),
        Map.entry(CityConstants.NORFOLK, 14.0),
        Map.entry(CityConstants.OKLAHOMA_CITY,2.5),
        Map.entry(CityConstants.OMAHA, 7.0),
        Map.entry(CityConstants.PHILADELPHIA,15.5),
        Map.entry(CityConstants.PHOENIX, 11.0),
        Map.entry(CityConstants.PITTSBURGH, 13.0),
        Map.entry(CityConstants.POCATELLO, 15.0),
        Map.entry(CityConstants.PORTLAND_ME,19.5),
        Map.entry(CityConstants.PORTLAND_OR,22.5),
        Map.entry(CityConstants.PUEBLO, 7.5),
        Map.entry(CityConstants.RAPID_CITY,12.5),
        Map.entry(CityConstants.RENO, 19.0),
        Map.entry(CityConstants.RICHMOND,14.0),
        Map.entry(CityConstants.SACRAMENTO, 19.5),
        Map.entry(CityConstants.SALT_LAKE_CITY,13.5),
        Map.entry(CityConstants.SAN_ANTONIO, 2.5),
        Map.entry(CityConstants.SAN_DIEGO, 14.5),
        Map.entry(CityConstants.SAN_FRANCISCO_OAKLAND,19.5),
        Map.entry(CityConstants.SEATTLE, 24.0),
        Map.entry(CityConstants.SHREVEPORT,2.0),
        Map.entry(CityConstants.SPOKANE, 21.0),
        Map.entry(CityConstants.ST_LOUIS,7.0),
        Map.entry(CityConstants.TAMPA, 12.5),
        Map.entry(CityConstants.TUCUMCARI, 5.0),
        Map.entry(CityConstants.WASHINGTON_DC, 14.0)
    );
}
