package com.bi.util.charts.payoff_charts;

import java.util.Map;

import com.bi.constants.CityConstants;

public class DesMoinesChart {
    public static Map<String,Double> map = Map.ofEntries(
        Map.entry(CityConstants.ALBANY,12.0),
        Map.entry(CityConstants.ATLANTA,9.5),
        Map.entry(CityConstants.BALTIMORE,11.5),
        Map.entry(CityConstants.BILLINGS, 10.5),
        Map.entry(CityConstants.BIRMINGHAM, 8.0),
        Map.entry(CityConstants.BOSTON, 14.0),
        Map.entry(CityConstants.BUFFALO, 9.0),
        Map.entry(CityConstants.BUTTE, 14.0),
        Map.entry(CityConstants.CASPER, 6.5),
        Map.entry(CityConstants.CHARLESTON, 13.0),
        Map.entry(CityConstants.CHARLOTTE, 11.5),
        Map.entry(CityConstants.CHATTENOOGA, 8.0),
        Map.entry(CityConstants.CHICAGO, 3.5),
        Map.entry(CityConstants.CINCINNATI, 6.5),
        Map.entry(CityConstants.CLEVELAND, 7.0),
        Map.entry(CityConstants.COLUMBUS , 7.0),
        Map.entry(CityConstants.DALLAS, 7.5),
        Map.entry(CityConstants.DENVER, 7.0),
        Map.entry(CityConstants.DETROIT,6.5),
        Map.entry(CityConstants.EL_PASO, 11.5),
        Map.entry(CityConstants.FARGO, 5.0),
        Map.entry(CityConstants.FORT_WORTH, 7.5),
        Map.entry(CityConstants.HOUSTON, 10.0),
        Map.entry(CityConstants.INDIANAPOLIS, 5.5),
        Map.entry(CityConstants.JACKSONVILLE,13.0),
        Map.entry(CityConstants.KANSAS_CITY, 2.0),
        Map.entry(CityConstants.KNOXVILLE, 9.0),
        Map.entry(CityConstants.LAS_VEGAS, 16.0),
        Map.entry(CityConstants.LITTLE_ROCK, 7.0),
        Map.entry(CityConstants.LOS_ANGELES, 19.5),
        Map.entry(CityConstants.LOUISVILLE, 6.0),
        Map.entry(CityConstants.MEMPHIS, 6.5),
        Map.entry(CityConstants.MIAMI, 16.5),
        Map.entry(CityConstants.MILWAUKEE, 3.5),
        Map.entry(CityConstants.MINNEAPOLIS_ST_PAUL,2.5),
        Map.entry(CityConstants.MOBILE, 10.0),
        Map.entry(CityConstants.NASHVILLE, 6.5),
        Map.entry(CityConstants.NEW_ORLEANS,10.5),
        Map.entry(CityConstants.NEW_YORK, 12.5),
        Map.entry(CityConstants.NORFOLK, 13.0),
        Map.entry(CityConstants.OKLAHOMA_CITY,5.5),
        Map.entry(CityConstants.OMAHA, 1.5),
        Map.entry(CityConstants.PHILADELPHIA,11.5),
        Map.entry(CityConstants.PHOENIX, 17.0),
        Map.entry(CityConstants.PITTSBURGH, 8.5),
        Map.entry(CityConstants.POCATELLO, 12.0),
        Map.entry(CityConstants.PORTLAND_ME,15.0),
        Map.entry(CityConstants.PORTLAND_OR,19.0),
        Map.entry(CityConstants.PUEBLO, 7.0),
        Map.entry(CityConstants.RAPID_CITY,7.0),
        Map.entry(CityConstants.RENO, 17.0),
        Map.entry(CityConstants.RICHMOND,12.0),
        Map.entry(CityConstants.SACRAMENTO, 18.0),
        Map.entry(CityConstants.SALT_LAKE_CITY,11.5),
        Map.entry(CityConstants.SAN_ANTONIO, 10.0),
        Map.entry(CityConstants.SAN_DIEGO, 20.5),
        Map.entry(CityConstants.SAN_FRANCISCO_OAKLAND,19.0),
        Map.entry(CityConstants.SEATTLE, 19.5),
        Map.entry(CityConstants.SHREVEPORT,8.0),
        Map.entry(CityConstants.SPOKANE, 16.5),
        Map.entry(CityConstants.ST_LOUIS,3.5),
        Map.entry(CityConstants.TAMPA, 14.5),
        Map.entry(CityConstants.TUCUMCARI, 9.0),
        Map.entry(CityConstants.WASHINGTON_DC, 11.0)
    );
}
