package com.bi.util.charts.payoff_charts;

import java.util.Map;

import com.bi.constants.CityConstants;

public class ElPasoChart {
    public static Map<String,Double> map = Map.ofEntries(
        Map.entry(CityConstants.ALBANY,22.0),
        Map.entry(CityConstants.ATLANTA,14.5),
        Map.entry(CityConstants.BALTIMORE,21.0),
        Map.entry(CityConstants.BILLINGS, 14.0),
        Map.entry(CityConstants.BIRMINGHAM, 13.0),
        Map.entry(CityConstants.BOSTON, 24.0),
        Map.entry(CityConstants.BUFFALO, 19.0),
        Map.entry(CityConstants.BUTTE, 16.0),
        Map.entry(CityConstants.CASPER, 9.5),
        Map.entry(CityConstants.CHARLESTON, 19.0),
        Map.entry(CityConstants.CHARLOTTE, 17.5),
        Map.entry(CityConstants.CHATTENOOGA, 15.5),
        Map.entry(CityConstants.CHICAGO, 14.0),
        Map.entry(CityConstants.CINCINNATI, 15.5),
        Map.entry(CityConstants.CLEVELAND, 17.5),
        Map.entry(CityConstants.COLUMBUS , 17.0),
        Map.entry(CityConstants.DALLAS, 6.5),
        Map.entry(CityConstants.DENVER, 7.5),
        Map.entry(CityConstants.DES_MOINES,11.5),
        Map.entry(CityConstants.DETROIT, 16.5),
        Map.entry(CityConstants.FARGO, 16.5),
        Map.entry(CityConstants.FORT_WORTH, 16.5),
        Map.entry(CityConstants.HOUSTON, 8.5),
        Map.entry(CityConstants.INDIANAPOLIS, 15.0),
        Map.entry(CityConstants.JACKSONVILLE,17.5),
        Map.entry(CityConstants.KANSAS_CITY, 9.5),
        Map.entry(CityConstants.KNOXVILLE, 15.5),
        Map.entry(CityConstants.LAS_VEGAS, 13.0),
        Map.entry(CityConstants.LITTLE_ROCK, 10.0),
        Map.entry(CityConstants.LOS_ANGELES, 8.0),
        Map.entry(CityConstants.LOUISVILLE, 15.0),
        Map.entry(CityConstants.MEMPHIS, 11.5),
        Map.entry(CityConstants.MIAMI, 21.5),
        Map.entry(CityConstants.MILWAUKEE, 14.5),
        Map.entry(CityConstants.MINNEAPOLIS_ST_PAUL,14.0),
        Map.entry(CityConstants.MOBILE, 13.0),
        Map.entry(CityConstants.NASHVILLE, 13.5),
        Map.entry(CityConstants.NEW_ORLEANS,11.5),
        Map.entry(CityConstants.NEW_YORK, 23.0),
        Map.entry(CityConstants.NORFOLK, 21.0),
        Map.entry(CityConstants.OKLAHOMA_CITY,7.0),
        Map.entry(CityConstants.OMAHA, 11.5),
        Map.entry(CityConstants.PHILADELPHIA,22.0),
        Map.entry(CityConstants.PHOENIX, 4.5),
        Map.entry(CityConstants.PITTSBURGH, 18.5),
        Map.entry(CityConstants.POCATELLO, 13.5),
        Map.entry(CityConstants.PORTLAND_ME,25.5),
        Map.entry(CityConstants.PORTLAND_OR,20.0),
        Map.entry(CityConstants.PUEBLO, 6.0),
        Map.entry(CityConstants.RAPID_CITY,13.0),
        Map.entry(CityConstants.RENO, 10.5),
        Map.entry(CityConstants.RICHMOND,20.5),
        Map.entry(CityConstants.SACRAMENTO, 12.0),
        Map.entry(CityConstants.SALT_LAKE_CITY,12.5),
        Map.entry(CityConstants.SAN_ANTONIO, 6.0),
        Map.entry(CityConstants.SAN_DIEGO, 8.0),
        Map.entry(CityConstants.SAN_FRANCISCO_OAKLAND,13.0),
        Map.entry(CityConstants.SEATTLE, 22.0),
        Map.entry(CityConstants.SHREVEPORT,8.5),
        Map.entry(CityConstants.SPOKANE, 20.0),
        Map.entry(CityConstants.ST_LOUIS,12.0),
        Map.entry(CityConstants.TAMPA, 19.5),
        Map.entry(CityConstants.TUCUMCARI, 3.5),
        Map.entry(CityConstants.WASHINGTON_DC, 20.5)
    );
}
